# Generated by Django 4.0.4 on 2023-07-28 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidoprestamo',
            name='usuario',
        ),
        migrations.AddField(
            model_name='pedidoprestamo',
            name='dni',
            field=models.CharField(default='', max_length=10),
        ),
    ]
